In [1]:
import pandas as pd
import numpy as np
import torch

In [2]:
from torch.utils.data import TensorDataset, DataLoader

In [3]:
df = pd.read_csv('housing.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [9]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [19]:
df.dropna(inplace=True)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20433 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  float64
 3   total_rooms         20433 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  float64
 6   households          20433 non-null  float64
 7   median_income       20433 non-null  float64
 8   median_house_value  20433 non-null  float64
 9   ocean_proximity     20433 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.7+ MB


In [21]:
df = pd.get_dummies(df, columns=['ocean_proximity'])

In [22]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value  \
0       322.0       126.0         8.3252            452600.0   
1      2401.0      1138.0         8.3014            358500.0   
2       496.0       177.0         7.2574            352100.0   
3       558.0       219.0         5.6431            341300.0   
4       565.0       259.0         3.8462            342200.0   

   ocean_proximity_<1H OCEAN  ocean_proximity_INLAND  ocean_proximity_ISLAND  \
0                          0                       0                       0   
1                          0                       0                       0   
2                          0                       0                       0   
3                          0                       0                       0   
4                          0                       0                       0   

   ocean_proximity_NEAR BAY  ocean_proximity_NEAR OCEAN  
0                         1                           0  
1                         1                           0  
2                         1                           0  
3                         1                           0  
4                         1                           0

In [23]:
from sklearn.preprocessing import MinMaxScaler

In [24]:
scaler = MinMaxScaler()

In [25]:
names = df.columns
d = scaler.fit_transform(df)

scaled_df = pd.DataFrame(d, columns=names)
scaled_df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0   0.211155  0.567481            0.784314     0.022331        0.019863   
1   0.212151  0.565356            0.392157     0.180503        0.171477   
2   0.210159  0.564293            1.000000     0.037260        0.029330   
3   0.209163  0.564293            1.000000     0.032352        0.036313   
4   0.209163  0.564293            1.000000     0.041330        0.043296   

   population  households  median_income  median_house_value  \
0    0.008941    0.020556       0.539668            0.902266   
1    0.067210    0.186976       0.538027            0.708247   
2    0.013818    0.028943       0.466028            0.695051   
3    0.015555    0.035849       0.354699            0.672783   
4    0.015752    0.042427       0.230776            0.674638   

   ocean_proximity_<1H OCEAN  ocean_proximity_INLAND  ocean_proximity_ISLAND  \
0                        0.0                     0.0                     0.0   
1                        0.0                     0.0                     0.0   
2                        0.0                     0.0                     0.0   
3                        0.0                     0.0                     0.0   
4                        0.0                     0.0                     0.0   

   ocean_proximity_NEAR BAY  ocean_proximity_NEAR OCEAN  
0                       1.0                         0.0  
1                       1.0                         0.0  
2                       1.0                         0.0  
3                       1.0                         0.0  
4                       1.0                         0.0

In [26]:
value = scaled_df['median_house_value']

In [27]:
value

0        0.902266
1        0.708247
2        0.695051
3        0.672783
4        0.674638
           ...   
20428    0.130105
20429    0.128043
20430    0.159383
20431    0.143713
20432    0.153403
Name: median_house_value, Length: 20433, dtype: float64

In [28]:
scaled_df.drop('median_house_value', axis=1, inplace=True)

### Linear regression

In [29]:
X_train = torch.tensor(scaled_df.values[::2], dtype=torch.float32)

In [30]:
X_test = torch.tensor(scaled_df.values[1::2], dtype=torch.float32)

In [31]:
y_train = torch.tensor(value.values[::2], dtype=torch.float32)

In [32]:
y_test = torch.tensor(value.values[1::2], dtype=torch.float32)

In [33]:
X_train

tensor([[0.2112, 0.5675, 0.7843,  ..., 0.0000, 1.0000, 0.0000],
        [0.2102, 0.5643, 1.0000,  ..., 0.0000, 1.0000, 0.0000],
        [0.2092, 0.5643, 1.0000,  ..., 0.0000, 1.0000, 0.0000],
        ...,
        [0.3247, 0.7375, 0.4706,  ..., 0.0000, 0.0000, 0.0000],
        [0.3118, 0.7322, 0.3137,  ..., 0.0000, 0.0000, 0.0000],
        [0.3098, 0.7258, 0.2941,  ..., 0.0000, 0.0000, 0.0000]])

In [34]:
batch_size = 10
dataset = TensorDataset(X_train, y_train)
# Randomly reading mini-batches
data_iter = DataLoader(dataset, batch_size, shuffle=True)

# Read a batch to see how it works
for X, y in data_iter:
    print(X, y)
    break

tensor([[0.7291, 0.0266, 0.4902, 0.0981, 0.0795, 0.0411, 0.0883, 0.3702, 1.0000,
         0.0000, 0.0000, 0.0000, 0.0000],
        [0.5876, 0.1552, 0.8824, 0.0451, 0.0560, 0.0250, 0.0548, 0.2724, 1.0000,
         0.0000, 0.0000, 0.0000, 0.0000],
        [0.2052, 0.6121, 1.0000, 0.0036, 0.0082, 0.0024, 0.0077, 0.0352, 0.0000,
         0.0000, 0.0000, 1.0000, 0.0000],
        [0.6036, 0.1668, 0.9216, 0.0368, 0.0456, 0.0190, 0.0470, 0.1885, 1.0000,
         0.0000, 0.0000, 0.0000, 0.0000],
        [0.2480, 0.4315, 0.6275, 0.0358, 0.0475, 0.0177, 0.0475, 0.2108, 1.0000,
         0.0000, 0.0000, 0.0000, 0.0000],
        [0.6972, 0.0701, 0.6078, 0.0318, 0.0340, 0.0195, 0.0380, 0.2405, 0.0000,
         0.0000, 0.0000, 0.0000, 1.0000],
        [0.6006, 0.1456, 0.6275, 0.0439, 0.0613, 0.0300, 0.0564, 0.2557, 1.0000,
         0.0000, 0.0000, 0.0000, 0.0000],
        [0.4641, 0.1987, 0.8431, 0.0307, 0.0552, 0.0168, 0.0487, 0.1455, 1.0000,
         0.0000, 0.0000, 0.0000, 0.0000],
        [0.2689,

In [35]:
inputs = X_train.shape[1]
model = torch.nn.Sequential(torch.nn.Linear(inputs, 1))

In [36]:
model

Sequential(
  (0): Linear(in_features=13, out_features=1, bias=True)
)

In [37]:
true_w = torch.randn(X_train.shape[1], dtype=torch.float32)
true_w

tensor([ 1.6311,  0.7610, -0.5561, -0.7958,  0.6209,  0.3079, -0.8601,  0.0206,
        -1.1350, -0.6347,  0.3178, -0.7108,  0.9803])

In [38]:
true_b = torch.zeros((1))
true_b

tensor([0.])

In [39]:
model[0].weight.data = true_w.clone().detach().requires_grad_(True).reshape((1, X_train.shape[1]))
model[0].bias.data = torch.tensor([true_b], requires_grad = True)

In [40]:
loss = torch.nn.MSELoss(reduction='mean')

In [41]:
trainer = torch.optim.SGD(model.parameters(), lr=0.001) #stohastic gradient descent

In [42]:
num_epochs = 100
for epoch in range(1, num_epochs + 1):
    for X, y in data_iter:
        trainer.zero_grad()
        l = loss(model(X).reshape(-1), y)
        l.backward()
        trainer.step()
    l = loss(model(X_train).reshape(-1), y_train)
    if epoch % 5 == 0:
        print('epoch %d, loss: %f' % (epoch, l.item()),'|\tw', model[0].weight.data, '|\tb', model[0].bias.data)

epoch 5, loss: 0.071955 |	w tensor([[ 1.3756,  1.0079, -0.2883, -0.7724,  0.6336,  0.3106, -0.8427,  0.2115,
         -0.4043, -0.7534,  0.3174, -0.3245,  0.0098]]) |	b tensor([0.0275])
epoch 10, loss: 0.047582 |	w tensor([[ 1.2401,  1.0647, -0.1931, -0.7483,  0.6493,  0.3129, -0.8253,  0.3431,
         -0.3498, -0.7233,  0.3172, -0.2433, -0.2104]]) |	b tensor([-0.0270])
epoch 15, loss: 0.041934 |	w tensor([[ 1.1744,  1.0614, -0.1297, -0.7222,  0.6699,  0.3175, -0.8036,  0.4622,
         -0.3430, -0.7094,  0.3170, -0.2421, -0.2635]]) |	b tensor([-0.0585])
epoch 20, loss: 0.038334 |	w tensor([[ 1.1281,  1.0410, -0.0865, -0.6970,  0.6913,  0.3223, -0.7814,  0.5659,
         -0.3477, -0.7002,  0.3168, -0.2572, -0.2805]]) |	b tensor([-0.0863])
epoch 25, loss: 0.035686 |	w tensor([[ 1.0908,  1.0170, -0.0530, -0.6733,  0.7128,  0.3271, -0.7595,  0.6567,
         -0.3534, -0.6926,  0.3165, -0.2727, -0.2884]]) |	b tensor([-0.1081])
epoch 30, loss: 0.033580 |	w tensor([[ 1.0610,  0.9941, -0.023

In [50]:
w = model[0].weight.data

In [51]:
b = model[0].bias.data

In [68]:
b

tensor([-0.1426])

In [112]:
def model_(x):
    return x @ w.T + b

In [113]:
y_predicted = model_(X_test)

In [118]:
y_predicted.T

tensor([[0.7870, 0.6565, 0.5276,  ..., 0.3307, 0.2549, 0.1909]])

## MSE

In [133]:
mse = (((y_test - y_predicted.T).sum())**2)/len(y_test)
mse

tensor(0.0240)