### Задание 1  
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [111]:
import numpy as np

n = int(input('Ввод N:'))

print(np.arange(n)[::-1])

Ввод N:10
[9 8 7 6 5 4 3 2 1 0]


### Задание 2  
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [82]:
n = int(input('Ввод N:'))

print(np.diag(np.arange(n,0,-1), k = 0))

np.sum(np.diag(np.arange(n,0,-1), k = 0)) #суммирование элеменитов массива

Ввод N:7
[[7 0 0 0 0 0 0]
 [0 6 0 0 0 0 0]
 [0 0 5 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 3 0 0]
 [0 0 0 0 0 2 0]
 [0 0 0 0 0 0 1]]


28

### Задание 3  
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [110]:
from numpy import linalg

a = ([[4,2,1],[1,3,0],[0,5,4]]) # коэффициенты в левой части уравнений
b = ([4,12,-3]) # коэффициенты в правой части уравнений

linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

### Задача 4 домашнего задания  
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [112]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [119]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [120]:


for item in users_stats:
    print(np.dot(item, next_user_stats)/((np.linalg.norm(item))*(np.linalg.norm(next_user_stats))))
    
    

0.19999999999999996
0.8451542547285165
0.3999999999999999
0.7905694150420948
0.3999999999999999
0.0
0.0
0.9486832980505138
0.0
0.0


### Решение

In [144]:
def closest_vector(users_stats, next_user_stats):
    
    blength = np.linalg.norm(next_user_stats)
    cosin = []
    
    for item in users_stats:
        alength = np.linalg.norm(item)
        
        cosin.append(np.dot(item, next_user_stats)/(alength*blength))
        
    
    return cosin.index(max(cosin))

closest_vector(users_stats, next_user_stats)

7