### Домашнее задание №2. Линейная алгебра. Матрицы

●Создайте случайную матрицу А1 размерностью 5 на 5  
●Транспонируйте матрицу A1  
●Найдите обратную матрицу для А1  
●Создайте диагональную матрицу - поэлементно перемножив единичнуюматрицу I и случайную матрицу A2 размерности 4 на 4  
●Создайте нулевую матрицу размерности 3 на 3  
●Для всех полученных матриц найдите: определитель, ранг и собственныезначения  
●Проанализируйте результаты

In [10]:
import numpy as np
import random

#### Случайная матрица А1 размерностью 5 на 5

In [75]:
A1 = np.random.randint(3,10, size = (5,5) ) #случайная матрица целых чисел 5x5 с диапазоном 3...10
A1

array([[4, 8, 8, 5, 7],
       [6, 6, 9, 3, 5],
       [8, 9, 9, 9, 4],
       [8, 8, 8, 9, 4],
       [9, 6, 3, 6, 6]])

In [80]:
print('Определитель A1: ',np.linalg.det(A1), '\nРанг А1:',np.linalg.matrix_rank(A1), 
     '\nСобственные значения A1:', np.linalg.eigvals(A1))

Определитель A1:  987.0000000000003 
Ранг А1: 5 
Собственные значения A1: [33.57833239  4.51152247 -3.8304934   1.18093844 -1.44029989]


#### Транспонированная матрица

In [78]:
A1T = np.transpose(A1) # транспонирование матрицы
A1T

array([[4, 6, 8, 8, 9],
       [8, 6, 9, 8, 6],
       [8, 9, 9, 8, 3],
       [5, 3, 9, 9, 6],
       [7, 5, 4, 4, 6]])

In [79]:
print('Определитель A1T: ',np.linalg.det(A1T), '\nРанг А1T:',np.linalg.matrix_rank(A1T), 
     '\nСобственные значения A1T:', np.linalg.eigvals(A1T))

Определитель A1T:  987.0000000000003 
Ранг А1T: 5 
Собственные значения A1T: [33.57833239  4.51152247 -3.8304934   1.18093844 -1.44029989]


#### Обратная матрица

In [84]:
A1_inv = np.linalg.inv(A1) # обратная матрица
A1_inv

array([[-0.19148936,  0.13069909,  0.15805471, -0.18237082,  0.13069909],
       [ 0.0212766 , -0.17325228,  1.39513678, -1.45592705,  0.16008105],
       [-0.0212766 ,  0.17325228, -0.39513678,  0.45592705, -0.16008105],
       [ 0.08510638, -0.12158055, -0.70516717,  0.89057751, -0.12158055],
       [ 0.19148936,  0.01215805, -0.72948328,  0.61094225,  0.01215805]])

In [94]:
print('Определитель A1_inv: ',np.linalg.det(A1_inv), '\nРанг A1_inv:',np.linalg.matrix_rank(A1_inv), 
     '\nСобственные значения A1_inv:', np.linalg.eigvals(A1_inv))

Определитель A1_inv:  0.0010131712259371813 
Ранг A1_inv: 5 
Собственные значения A1_inv: [ 0.84678419 -0.69429985 -0.26106297  0.22165466  0.02978111]


In [88]:
np.round((np.matmul(A1, A1_inv)),2) # произведение исходной матрицы с обратной должно давать единичную матрицу

array([[ 1.,  0., -0.,  0.,  0.],
       [-0.,  1., -0.,  0., -0.],
       [ 0., -0.,  1., -0.,  0.],
       [ 0., -0., -0.,  1., -0.],
       [-0., -0.,  0.,  0.,  1.]])

#### Создайте диагональную матрицу - поэлементно перемножив единичную матрицу I и случайную матрицу A2 размерности 4 на 4

In [90]:
A2 = np.random.random([4,4])
A2

array([[0.74211807, 0.86109788, 0.41173365, 0.91797848],
       [0.36941026, 0.48012421, 0.73763026, 0.64023776],
       [0.37511461, 0.53568124, 0.82809159, 0.408788  ],
       [0.65348561, 0.32214556, 0.97133121, 0.87190426]])

In [92]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [93]:
A2I = A2*I
A2I

array([[0.74211807, 0.        , 0.        , 0.        ],
       [0.        , 0.48012421, 0.        , 0.        ],
       [0.        , 0.        , 0.82809159, 0.        ],
       [0.        , 0.        , 0.        , 0.87190426]])

In [95]:
print('Определитель A2I: ',np.linalg.det(A2I), '\nРанг A2I:',np.linalg.matrix_rank(A2I), 
     '\nСобственные значения A2I:', np.linalg.eigvals(A2I))

Определитель A2I:  0.2572608972815545 
Ранг A2I: 4 
Собственные значения A2I: [0.74211807 0.48012421 0.82809159 0.87190426]


#### Нулевая матрица размерности 3 на 3

In [98]:
A3 = np.zeros([3,3])
A3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [99]:
print('Определитель A3: ',np.linalg.det(A3), '\nРанг A3:',np.linalg.matrix_rank(A3), 
     '\nСобственные значения A3:', np.linalg.eigvals(A3))

Определитель A3:  0.0 
Ранг A3: 0 
Собственные значения A3: [0. 0. 0.]
